### ISSUE TITLE
babel doesn't export module in commonjs style

### ISSUE THREAD

**Issue by mderazon** [urbancups/node-sheets#2]
See here
http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default

After installing, need to access the module as

``` js
const Sheets = require('node-sheets').default
```

Instead of just

``` js
const Sheets = require('node-sheets')
```

I guess since this is going to be used in node, we need to change the behaviour to commonjs style and instead of es6 modules.

See this for a possible solution
http://stackoverflow.com/a/33683495/599912

**Comment by LongLiveCHIEF** [comment]
Node already decided it wasn't going to introduce native support for es6 modules. Instead, they're going to support a `mjs` (module js) file extension.

However, you can still get the best of both worlds, by using named exports instead of assigning a value to `module.exports`.  (this is the same thing as creating an [alias for a module](https://nodejs.org/api/modules.html#modules_exports_alias)).

This is actually quite simple for your code base.  Just change:

```
// old way
exports default class Sheets { ... }

// new way
exports class Sheets { ... }
```

You still use the static `import` the same way you are showing in your docs now, but with the added benefit of being commonJS compatible, with both destructured requires *and* normal requires!

```
// babel/es7 - works with a slight change to the call!
import {Sheets} from 'node-sheets';

// babel: commonJS/es6
var {Sheets} = require('node-sheets');

// native node v6
var Sheets = require('node-sheets').Sheets;
```

**Comment by mderazon** [comment]
Interesting,

> Node already decided it wasn't going to introduce native support for es6 modules

Do you have a link where it's mentioned ? I saw that V8 just landed support es6 modules so I assumed it will make it's way to Node.

I will play with your example a little and see if I can get it to work.
Thanks!

**Comment by LongLiveCHIEF** [comment]
Yeah, the links are in my comment.
